# Generated by Django 5.2.17 on 2026-09-20 14:02

from django.conf import settings
from django.db import migrations, models


def repair_inverted_periods(apps, schema_editor):
    """Guard the CHECK constraint below against any pre-existing bad row.

    Generation never persisted rows before this release, so this should match
    nothing; it exists so the deploy cannot abort on legacy data.
    """
    FollowUpReport = apps.get_model("followup", "FollowUpReport")
    for row in FollowUpReport.objects.filter(period_start__gt=models.F("period_end")):
        row.period_start, row.period_end = row.period_end, row.period_start
        row.save(update_fields=["period_start", "period_end"])


def noop(apps, schema_editor):
    """Nothing to undo: the repair only normalises row order."""


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0001_initial'),
        ('organizations', '0002_remove_require_head_review_before_verification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(repair_inverted_periods, noop),
        migrations.AddField(
            model_name='followupreport',
            name='executive_summary',
            field=models.JSONField(blank=True, default=dict, help_text='Narrative frozen alongside the snapshot, in the generation language.'),
        ),
        migrations.AddField(
            model_name='followupreport',
            name='language',
            field=models.CharField(default='ar', max_length=5),
        ),
        migrations.AddIndex(
            model_name='followupreport',
            index=models.Index(fields=['municipality', '-created_at'], name='followup_fo_municip_39bdc5_idx'),
        ),
        migrations.AddConstraint(
            model_name='followupreport',
            constraint=models.CheckConstraint(condition=models.Q(('period_start__lte', models.F('period_end'))), name='followup_period_start_before_end'),
        ),
    ]
