# Generated by Django 5.2.17 on 2026-08-16 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deadline_approaching', 'Deadline approaching'), ('due_today', 'Due today'), ('overdue', 'Overdue'), ('response_needed', 'Response needed'), ('returned', 'Returned'), ('action_required', 'Action required'), ('status_change', 'Status change')], max_length=30)),
                ('message', models.TextField(blank=True)),
                ('dedupe_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='audits.recommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReminderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset_days', models.IntegerField(help_text='Negative = before deadline, 0 = due today, positive = days overdue.')),
                ('enabled', models.BooleanField(default=True)),
                ('recipient_role', models.CharField(choices=[('employee', 'Responsible employee'), ('department_head', 'Department head'), ('audit', 'Internal audit (escalation)')], default='employee', max_length=20)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_rules', to='organizations.municipality')),
            ],
            options={
                'ordering': ['offset_days'],
                'unique_together': {('municipality', 'offset_days', 'recipient_role')},
            },
        ),
    ]
