# Generated by Django 5.2.17 on 2026-08-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrecord',
            name='approval_type',
            field=models.CharField(choices=[('audit_approval', 'Audit approval'), ('council_ratification', 'Council ratification'), ('head_implementation_review', 'Department review of implementation'), ('closure_review', 'Audit closure review'), ('closure_council', 'Council closure decision')], max_length=30),
        ),
    ]
