# Generated by Django 5.2.17 on 2026-08-16 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('engagement_type', models.CharField(choices=[('advisory', 'Advisory'), ('assurance', 'Assurance')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_response', 'Pending department response'), ('under_review', 'Under audit review'), ('pending_council', 'Pending council ratification'), ('ratified', 'Ratified by council')], default='draft', max_length=30)),
                ('response_deadline', models.DateField(blank=True, help_text="Deadline for the department's management response.", null=True)),
                ('council_approval_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='organizations.department')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='organizations.municipality')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('root_cause', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('priority_score', models.IntegerField(default=0, help_text='Ranks follow-up priority.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_response', 'Pending department response'), ('audit_review', 'Response under audit review'), ('returned_for_revision', 'Returned to department for revision'), ('pending_council', 'Pending council ratification'), ('approved_for_implementation', 'Approved for implementation'), ('action_plan_required', 'Action plan required'), ('action_plan_review', 'Action plan under review'), ('revision_required', 'Action plan revision required'), ('action_plan_approved', 'Action plan approved'), ('in_progress', 'In progress'), ('submitted_for_verification', 'Submitted for audit verification'), ('returned_insufficient', 'Returned - insufficient evidence'), ('partial', 'Partially implemented'), ('closed', 'Closed')], default='draft', max_length=40)),
                ('resolution', models.CharField(blank=True, choices=[('implemented', 'Implemented and verified'), ('disagreement_accepted', 'Disagreement accepted')], help_text='Set when the recommendation reaches a terminal state.', max_length=30)),
                ('is_recurring', models.BooleanField(default=False)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('recurrence_confirmed', models.BooleanField(default=False, help_text='Human-in-the-loop confirmation by internal audit.')),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='audits.auditreport')),
                ('similar_recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrences', to='audits.recommendation')),
            ],
            options={
                'ordering': ['-priority_score', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditreport',
            index=models.Index(fields=['municipality', 'status'], name='audits_audi_municip_9a6649_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['status'], name='audits_reco_status_d08fae_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['risk_level'], name='audits_reco_risk_le_05c3ef_idx'),
        ),
    ]
