# Generated by Django 5.2.17 on 2026-08-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_response', 'Pending department response'), ('audit_review', 'Response under audit review'), ('returned_for_revision', 'Returned to department for revision'), ('pending_council', 'Pending council ratification'), ('approved_for_implementation', 'Approved for implementation'), ('action_plan_required', 'Action plan required'), ('action_plan_review', 'Action plan under review'), ('revision_required', 'Action plan revision required'), ('action_plan_approved', 'Action plan approved'), ('in_progress', 'In progress'), ('pending_head_review', 'Pending department review of implementation'), ('submitted_for_verification', 'Submitted for audit verification'), ('returned_insufficient', 'Returned - insufficient evidence'), ('partial', 'Partially implemented'), ('reopened', 'Reopened by council for further action'), ('closure_review', 'Recommendation closure review'), ('pending_closure_council', 'Pending council closure review'), ('closed', 'Closed')], default='draft', max_length=40),
        ),
    ]
