# Generated by Django 5.2.17 on 2026-08-16 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'municipalities',
            },
        ),
        migrations.CreateModel(
            name='WorkflowPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_plan_with_response', models.BooleanField(default=False)),
                ('require_head_review_before_verification', models.BooleanField(default=False)),
                ('municipality', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_policy', to='organizations.municipality')),
            ],
            options={
                'verbose_name_plural': 'workflow policies',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organizations.municipality')),
            ],
            options={
                'unique_together': {('municipality', 'name')},
            },
        ),
    ]
