# Generated by Django 5.2.17 on 2026-08-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowpolicy',
            name='require_head_review_before_verification',
        ),
    ]
